### ISSUE TITLE
Feature request - reload data after a while

### ISSUE THREAD

**Issue by Frooodle** [revenz/Fenrus#124]
As a user i would want to be able to open my dash and view up to date information, currently info is only updated after a set time fenrus is open, even if that info is days old unless the page is open for a set time the displayed info will be vastly out of date.

Can you have it so data is refreshed regardless every 12-24 hours if not been ran for that duration or maybe some config based thing.
Another solution would have the timers work outside of the window itself so that when you next open  fenrus after say 30 minutes, all timers that are less than 30 minutes intervals are called.

**Comment by revenz** [comment]
the data is stored in localstorage, ie its fetched by the browser, not the server.  so unless the page is opened, it cannot download more data.

**Comment by Frooodle** [comment]
Sorry for miswording I understand the info wouldn't be instantly available but I would want to queries to be run when page is opened after long time etc

**Comment by revenz** [comment]
it caches the last data it fetched so when the page loads it has something to show.  but then it should trigger an update if that data is too old instantly, or wait until its next interval.

this only happens if the page has focus though.  if you click outside the browser tab it will pause updates (so if you have it open in a background tab its not just constantly running queries)
