### ISSUE TITLE
Wrong link definition in page for managing Groups and System groups

### ISSUE THREAD

**Issue by loli71** [revenz/Fenrus#188]
Hello,

I found a bug in Version 23.06.3.985, in page for managing groups (same in page for managing system groups), the link on the "Edit" icon button is not good regarding the link on the name for the same group (see screenshot below)

On name link is "http://nas:5301/settings/**groups**/46f46366-cded-49fd-b57e-eb5da69a55a0"
On edit icon button link is "http://nas:5301/settings/**dashboards**/46f46366-cded-49fd-b57e-eb5da69a55a0"

![image](https://github.com/revenz/Fenrus/assets/8059521/32d1953e-df1a-4fbc-a5b8-92a6e5b6e1a4)

**Comment by permster** [comment]
This may be related to #178.  When you click the edit button on the right with the bad link it causes the page to not respond which you then have to refresh the browser window to get it working again.

**Comment by revenz** [comment]
fixed

**Comment by jre08** [comment]
This issue seems to have popped back up.  I was experiencing  this in the 23.08 (docker) version.  The page would freeze in browser (MS Edge)  after trying to delete a group (System or user)  ,No link would work until a refresh was preformed.  This does not seem to be an issue if running Chrome.  

The console error I was receiving was:
There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions by setting 'DetailedErrors: true' in 'appSettings.Development.json' or set 'CircuitOptions.DetailedErrors'.

After fiddling around with it a little while I decided to update to the  'revenz/fenrus:develop' (24.04) docker image, and it also was having issues with MS EDGE.          Chrome is working fine.
