### ISSUE TITLE
[Feature Request] Support for checkbox parameters

### ISSUE THREAD

**Issue by Frooodle** [revenz/Fenrus#29]
As a user there are sometimes parameters for smart apps that are a simple on/off for choosing to show or not show a certain value etc..
A checkbox parameter would be the best way of presenting this

Example usecases I have in mind is right now radarr's 'missing' result is for the filter hasFile=false but this is a useless stat for many people since many may as want to filter it by 'Monitored' or 'isAvailable'. 
The total missing stat is still useful for some people so the thought of have 3 parameters with checkboxs on which filters to apply would be useful.

**Comment by revenz** [comment]
for this specific thing, you could make 2 selects, each saying what stat to show here.     This means they could select the same stat twice, but that would be silly so a user wouldn't do that (and if they did, they want to do that, for some odd reason).

I'm reluctant to add checkboxes due to design reasons and wanting to use a slider, which is available.

A checkbox group however I would add (similar to in FileFlows and the Subtitle Remover node)

**Comment by Frooodle** [comment]
Sorry misphrased the usecase it would not be to show hasFile vs isAvailable but instead what additional filters to allow to the already existing hasFile filter. Since personally the "Missing" result should show which are missing but COULD be retrieved etc

But regardless.. 2 selects with a enable/disable filter option would achieve same so totally doable now but I thought checkbox might be nicer. Either work so im fine without👍 

 Not sure what you refer to as a checkbox group, I am a Tdarr user :') haha

**Comment by Frooodle** [comment]
I'll migrate to Fileflows one day, im not another spy :P
